//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSim.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelPartnerManagement
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> PTD { get; set; }
        public Nullable<decimal> DistributorMargin { get; set; }
        public Nullable<decimal> RetailerMargin { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
